sudo: false
language: python
matrix:
  include:
    - python: '2.7'
      install:
      - pip install flake8
      script: flake8
    - python: '3.5'
      install:
      - pip install flake8
      script: flake8      
    - python: '3.6'
      install:
      - pip install flake8
      script: flake8
